[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.pdo_mysql", "php82Extensions.gd"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "mkdir -p cache",
    "chmod -R 775 storage cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"